server.port=${SERVER_PORT:8080}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH:/api}
db.driver=com.mysql.cj.jdbc.Driver
db.url=${DB_URL:jdbc:mysql://localhost:3306/numpty}
db.username=${DB_USERNAME:}
db.password=${DB_PASSWORD:}
db.max_pool_size=10
db.connection_timeout=5000
db.max_lifetime=1800000
db.init.schema=${DB_INIT_SCHEMA:true}
db.init.schema.location=${DB_INIT_SCHEMA_LOCATION:schema.sql}
mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
mongodb.database=${MONGODB_DATABASE:main}
mongodb.conn.timeout=3000
mongodb.read.timeout=10000
mongodb.server_selection.timeout=3000
mongodb.credential.database=${MONGODB_CREDENTIAL_DATABASE:main}
mongodb.credential.username=${MONGODB_CREDENTIAL_USERNAME:}
mongodb.credential.password=${MONGODB_CREDENTIAL_PASSWORD:}
redis.host=${REDIS_HOST:127.0.0.1}
redis.port=${REDIS_PORT:6379}
redis.password=${REDIS_PASSWORD:}
redis.timeout=2000
redis.pool.max_connection=10
redis.pool.max_idle=5
jwt.secret=${JWT_SECRET:default-secret-key-value-must-be-long-enough}