[redis]
numpty-redis

[mongo]
numpty-mongo

[mysql]
numpty-mysql

[api]
numpty-api

[worker]
numpty-worker

[bff]
numpty-bff

[web]
numpty-web

[data:children]
redis
mongo
mysql

[data:vars]
ansible_python_interpreter=/usr/bin/python3

[app:children]
api
worker
bff
web

[app:vars]
ansible_python_interpreter=/usr/bin/python3